# Build settings

source: .
destination: ./_site
markdown: kramdown
# don't change the following; coderay will break the embedded
# annotations.
kramdown:
  enable_coderay: false
permalinks: pretty
# safe: true
markdown_ext: md

##############################################################################

# Site settings

name: Physical interaction annotation docs
baseurl: "/annodoc-physical-protein-interaction-corpus"
homeurl: "https://katnastou.github.io/annodoc-physical-protein-interaction-corpus/"
editurl: "https://github.com/katnastou/annodoc-physical-protein-interaction-corpus/edit/gh-pages"
issueurl: "https://github.com/katnastou/annodoc-physical-protein-interaction-corpus/issues"

##############################################################################

# Collection settings

collections:
  entity:
    output: true
  relation:
    output: true
